stage: 4

model:
  dino:
    # DINOv2 backbone (will use timm or hub fallback). Consider vit_base_patch16_224.dino for lower memory.
    name: dinov2_vitb14
  clip:
    name: ViT-L-14
    pretrained: openai
  sam:
    # Use SAM2 decoder (string must contain "sam2"). Choose a small variant for memory.
    type: sam2_hiera_small
    # Set these to your local SAM2 config/checkpoint paths (Hydra YAML + weights).
    # You can override via CLI if preferred.
    config: /path/to/sam2/configs/sam2_hiera_s.yaml
    # checkpoint: /path/to/sam2_hiera_s.pth
    # SAM decoders expect 256‑dim image embeddings
    embed_dim: 256

data:
  format: voc
  root: /path/to/HAM10000_VOC               # override via CLI
  split: train                              # or a custom list.txt
  binary: true
  text: "skin lesion"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  # Per‑GPU batch size (total batch = nproc_per_node * batch_size)
  batch_size: 2
  lr: 2.0e-5           # lower LR for full DINO unfreeze
  lora_lr: 3.0e-4      # still used for SAM LoRA if enabled
  wd: 1.0e-4
  amp: true            # enable mixed precision on CUDA
  amp_dtype: bf16      # set to fp16 if bf16 unsupported

loss:
  clip_align_weight: 0.1
  ssl_weight: 0.05

epochs: 50

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    # Stage 4 unfreezes DINO fully; keep DINO LoRA disabled
    enable: false
    last_k_blocks: 8
    rank: 16
    alpha: 16
    dropout: 0.0

output:
  dir: experiments/ham10000_sam2_dinov2_stage4_dualgpu

checkpoint:
  dir: experiments/ham10000_sam2_dinov2_stage4_dualgpu/checkpoints
  save_best: true
  save_latest: true
  keep_per_epoch: false

distributed:
  # Use torchrun for multi‑GPU DDP (recommended). Leave DP off.
  use_data_parallel: false

eval:
  # Dual‑circle eval can be enabled via CLI overrides
  dual_circle:
    enable: false
    # image_dir: /path/to/no_circle_images
    # circle_dir: /path/to/circle_masks
    # ignore_rect_dir: /path/to/extra_ignore_rectangles
    # output_dir: experiments/ham10000_sam2_dinov2_stage4_dualgpu/eval/dual_circle_results.csv
