stage: 4

model:
  backbone:
    type: swin
    name: swin_large_patch4_window7_224
    pretrained: true
    out_index: 3         # selects final stage tokens (1536-dim)
  clip:
    name: ViT-L-14
  sam:
    # SAM2 variant: supply both Hydra config and checkpoint paths
    type: sam2_hiera_large
    config: checkpoints/sam2/sam2_hiera_large.yaml
    checkpoint: checkpoints/sam2/sam2_hiera_large.pt

data:
  format: voc
  root: /path/to/HAM10000_VOC
  split: train
  binary: true
  text: "skin lesion"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  batch_size: 1          # large backbone + SAM2 is memory heavy; increase if GPUs permit
  lr: 2.0e-5
  lora_lr: 3.0e-4
  wd: 1.0e-4

loss:
  clip_align_weight: 0.1
  ssl_weight: 0.05

epochs: 150

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    enable: false        # fully unfreeze backbone at stage 4
    last_k_blocks: 8
    rank: 16
    alpha: 16
    dropout: 0.0
