stage: 3

model:
  backbone:
    type: swin
    name: swin_base_patch4_window7_224
    pretrained: true
    out_index: 3
  clip:
    name: ViT-L-14
  sam:
    type: vit_b
    # checkpoint: /path/to/sam_vit_b.pth

data:
  root: /path/to/images
  masks: /path/to/masks
  text: "bruise"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  batch_size: 4
  lr: 5.0e-5
  lora_lr: 3.0e-4
  wd: 1.0e-4

loss:
  clip_align_weight: 0.1
  ssl_weight: 0.05

epochs: 100

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    enable: false  # switch on if you add Swin LoRA support
    last_k_blocks: 8
    rank: 16
    alpha: 16
    dropout: 0.0
