stage: 1

model:
  backbone:
    type: swin
    name: swin_base_patch4_window7_224
    pretrained: true
    out_index: 3  # uses the 1/32 stride stage; adjust if you need denser grids
  clip:
    name: ViT-L-14
  sam:
    type: vit_b
    # checkpoint: /path/to/sam_vit_b.pth  # optional

data:
  root: /path/to/images
  masks: /path/to/masks  # optional or pseudo-labels
  text: "bruise"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  batch_size: 4
  lr: 1.0e-4
  lora_lr: 3.0e-4
  wd: 1.0e-4

loss:
  clip_align_weight: 0.0
  ssl_weight: 0.0

epochs: 1

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    enable: false  # set true if you add Swin-specific LoRA targets later
