stage: 4

model:
  dino:
    name: vit_base_patch16_224.dino
  clip:
    name: ViT-L-14
  sam:
    type: vit_b
    # checkpoint: /path/to/sam_vit_b.pth  # optional

data:
  root: /path/to/images
  masks: /path/to/masks
  text: "bruise"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  batch_size: 4
  lr: 2.0e-5         # lower LR for full DINO unfreeze
  lora_lr: 3.0e-4     # still used for SAM LoRA if enabled
  wd: 1.0e-4

loss:
  clip_align_weight: 0.1
  ssl_weight: 0.05

epochs: 50

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    enable: false      # disable DINO LoRA for full unfreeze
    last_k_blocks: 8
    rank: 16
    alpha: 16
    dropout: 0.0

