stage: 2

model:
  dino:
    name: vit_base_patch16_224.dino  # or vit_large_patch14_dinov2.lvd142m if available
  clip:
    name: ViT-L-14
  sam:
    type: vit_b
    # checkpoint: /path/to/sam_vit_b.pth

data:
  root: /path/to/images
  masks: /path/to/masks  # can mix pseudo-labels
  text: "bruise"
  resize: 256
  crop: 224
  num_workers: 4

optim:
  batch_size: 4
  lr: 1.0e-4
  lora_lr: 5.0e-4
  wd: 1.0e-4

loss:
  clip_align_weight: 0.05
  ssl_weight: 0.1

epochs: 3

lora:
  sam:
    enable: true
    rank: 8
    alpha: 8
    dropout: 0.0
    targets: ["attn", "mlp", "proj", "lin"]
  dino:
    enable: true
    last_k_blocks: 4
    rank: 16
    alpha: 16
    dropout: 0.0

